public class NHR_Constant {
    public static final String ZENSHYA = '全社';
    public static final String CON1 = '金属製建具工事';
    public static final String CON2 = '金属工事';
    public static final String CON3 = '内装仕上工事';
    public static final String CON_OTHER = 'その他';
    public static final String TOTAL = '合計';
    public static final String PERSON = '個人';
    public static final String ACTUAL = '実績';
    public static final String BUDGET = '予算';
    
    public static final String ST_SUB1 = '(A)1000t以上';
    public static final String ST_SUB2 = '(B)500-1000t未満';
    public static final String ST_SUB3 = '(C)250-500t未満';
    public static final String ST_SUB4 = '(D)50-250t未満';
    public static final String ST_SUB5 = '(E)50t未満';
    public static final String NUM = '件数';
    public static final String QUANTITY  = '数量';
    
    public static final String UNIT1 = '営業部';
    public static final String UNIT2 = 'チーム';
    public static final String UNIT3 = '個人';
    public static final String UNIT4 = '自分';
    
    public static final String BATCHNAME_AOT = 'AccountOrderTarget';
    public static final String BATCHNAME_AST = 'AccountSalesTarget';
    public static final String BATCHNAME_CO = 'ConOrder';
    public static final String BATCHNAME_COO = 'ConOppOrder';
    public static final String BATCHNAME_SRM1 = 'SalesReviewMeeting_1';
    public static final String BATCHNAME_SRM2 = 'SalesReviewMeeting_2';
    public static final String BATCHNAME_SRM3 = 'SalesReviewMeeting_3';
    public static final String BATCHNAME_OAL = 'OrderAmountListOsaka';
    public static final String BATCHNAME_SLSALES1 = 'SL_Sales1';
    public static final String BATCHNAME_SLSALES2 = 'SL_Sales2';
    public static final String BATCHNAME_SLSALES3 = 'SL_Sales3';
    public static final String BATCHNAME_SLSALES4 = 'SL_Sales4';
    //スチール
    public static final String BATCHNAME_ST_R = 'ST_R';
    public static final String BATCHNAME_ST_OSD1 = 'ST_OSD1';
    public static final String BATCHNAME_ST_OSD2 = 'ST_OSD2';
    public static final String BATCHNAME_ST_OSD3 = 'ST_OSD3';
    public static final String BATCHNAME_ST_OSD4 = 'ST_OSD4';
    //加工数量実績および予定
    public static final String BATCHNAME_ST_AP = 'ST_AP';
    
    public static final String BATCHNAME_JU_KPI = 'JU_KPI';
}