@isTest
public class NHR_ConstantTest {

    @isTest static void test() {
        String testStr ;
        testStr =NHR_Constant.ZENSHYA;
        testStr = NHR_Constant.CON1;
        testStr = NHR_Constant.CON2;
        testStr = NHR_Constant.CON3;
        testStr = NHR_Constant.CON_OTHER;
        testStr = NHR_Constant.TOTAL;
        testStr = NHR_Constant.PERSON;
        testStr = NHR_Constant.ACTUAL;
        
        testStr = NHR_Constant.BUDGET;
        testStr = NHR_Constant.BATCHNAME_AOT;
        testStr = NHR_Constant.BATCHNAME_AST;
        testStr = NHR_Constant.BATCHNAME_CO;
        testStr = NHR_Constant.BATCHNAME_COO;
        testStr = NHR_Constant.BATCHNAME_SRM1;
        testStr = NHR_Constant.BATCHNAME_SRM2;
        testStr = NHR_Constant.BATCHNAME_SRM3;
        
    }
}